### ISSUE TITLE
[8.0] users_log: missing ACL for res.users.log

### ISSUE THREAD

**Issue by alexis-via** [geotechnosoft/user_logs#1]
There is no ACL (ir.model.access) for the object res.users.log. And the record is created with the uid of the user that logs in (cf https://github.com/geotechnosoft/user_logs/blob/8.0/user_logs/users.py#L33), so when a regular user (not the admin user) logs-in, the res.users.log record is not created and you have in the odoo server logs:

```
2017-06-14 14:15:52,652 14158 WARNING o8_test1 openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: create, uid: 4, model: res.users.log
```
I think the best way would be:
- create the res.users.log with SUPERUSER_ID (not with the uid of the logged-in user)
- add an ACL that grants read access on res.users.log to at least one group

So, for me, in it's current state, the module user_logs doesn't work. And it seems that when using it, there are other warning in odoo's logs:

```
2017-06-14 14:16:40,947 14158 WARNING o8_test1 openerp.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.
```

**Comment by geotechnosoft** [comment]
Hi thanks for the suggestion, Read ACL has been given to all users and menu access is available only for **User Log Create** group.
